### ISSUE TITLE
Publish the repository server

### ISSUE THREAD

**Issue by ThePhoenix47** [jaredallard/ccdocker#6]
As the repository was shut down, would it be possible to publish the source of the server behind it? I would really like to have the possibility to host it myself and play around with it. I would just have to change "server" in ccdocker.lua, wouldn't I?

**Comment by jaredallard** [comment]
Yes you would! I think I may have removed the server source... Regardless its a quick rebuild of it so I'll see what I can do!

**Comment by ThePhoenix47** [comment]
Thank you.

**Comment by ThePhoenix47** [comment]
This was months ago. Any update on this, or should I consider it dead?

**Comment by jaredallard** [comment]
Jfc, I don't know how I forgot about this, I'll try to get it rebuilt by tonight. Wanted a quick project to work on today anyways

**Comment by jaredallard** [comment]
@ThePhoenix47 https://github.com/cswarm/ccdockerd

**Comment by jaredallard** [comment]
Closing
